/* Babylon 8.26 renderer. Articulated geometry adapted from Atelier du guerrier.
 * Shared rigid-part templates / instances; not sprites, no agent or framework.
 */
(function(g){'use strict';
const B=g.BABYLON,V=B.Vector3,{heightAt}=g.RDNBattle;
const color=hex=>B.Color3.FromHexString(hex),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class BattleView{
 constructor(canvas,battle){this.canvas=canvas;this.battle=battle;this.units=new Map();this.projectiles=new Map();this.effects=[];this.factories={};this.time=0;this.mode='tactical';
 this.engine=new B.Engine(canvas,true,{stencil:true,antialias:true,preserveDrawingBuffer:true});this.engine.setHardwareScalingLevel(1/Math.min(devicePixelRatio||1,1.5));
 const scene=this.scene=new B.Scene(this.engine);scene.clearColor=new B.Color4(.085,.123,.108,1);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.012;scene.fogColor=color('#748071');scene.ambientColor=color('#586052');
 this.camera=new B.ArcRotateCamera('strategic',-Math.PI/2,.71,35,new V(0,.1,0),scene);this.camera.minZ=.1;this.camera.maxZ=180;this.camera.fov=.68;this.radius=35;
 const sky=new B.HemisphericLight('overcast',new V(.15,1,.2),scene);sky.intensity=.80;sky.groundColor=color('#3b4131');
 const sun=new B.DirectionalLight('late sun',new V(-.65,-1,.4),scene);sun.position=new V(18,30,-18);sun.intensity=1.35;sun.diffuse=color('#fff0ce');
 this.shadow=new B.ShadowGenerator(1024,sun);this.shadow.useBlurExponentialShadowMap=true;this.shadow.blurKernel=8;this.shadow.bias=.0008;this.shadow.normalBias=.025;sun.shadowMinZ=1;sun.shadowMaxZ=85;
 this.m={};const mat=(name,hex,metal=0,rough=.86)=>{const m=new B.PBRMaterial(name,scene);m.albedoColor=color(hex);m.metallic=metal;m.roughness=rough;this.m[name]=m;return m;};
 mat('cloth','#47534b');mat('blue','#405b65');mat('red','#773f36');mat('leather','#59402e');mat('strap','#b28a57');mat('skin','#c1a082');mat('beard','#58483a');mat('steel','#a7b2ac',.65,.38);mat('edge','#c2c9ba',.72,.27);mat('iron','#414c49',.52,.52);mat('gold','#c2a362',.65,.43);mat('wood','#8b6746');mat('pale','#d3c6a4');mat('pine','#324d3b');mat('pineLight','#536446');mat('stone','#747b68');
 const land=new B.StandardMaterial('living soil',scene);land.diffuseColor=B.Color3.White();land.specularColor=B.Color3.Black();this.m.land=land;
 this.buildTerrain();this.buildFlags();this.destination=B.MeshBuilder.CreateTorus('destination',{diameter:1.1,thickness:.028,tessellation:48},scene);this.destination.material=this.m.gold;this.destination.isPickable=false;this.destination.setEnabled(false);this.destinationAge=99;
 this.engine.resize();
 }
 primitive(kind,name,size,pos,mat){let mesh;if(kind==='box')mesh=B.MeshBuilder.CreateBox(name,{width:size[0],height:size[1],depth:size[2]},this.scene);else if(kind==='sphere'){mesh=B.MeshBuilder.CreateSphere(name,{diameter:1,segments:8},this.scene);mesh.scaling.set(...size);}else mesh=B.MeshBuilder.CreateCylinder(name,{diameterTop:size[0]*2,diameterBottom:size[1]*2,height:size[2],tessellation:size[3]||12},this.scene);mesh.position.set(...pos);mesh.material=typeof mat==='string'?this.m[mat]:mat;mesh.isPickable=false;return mesh;}
 group(name,build){const arr=[],add=(kind,size,pos,mat)=>{const mesh=this.primitive(kind,name,size,pos,mat);arr.push(mesh);return mesh;};build(add,arr);arr.forEach(m=>m.computeWorldMatrix(true));const merged=B.Mesh.MergeMeshes(arr,true,true,undefined,false,true);if(!merged)throw new Error('Assemblage 3D impossible : '+name);merged.name=name;merged.isVisible=false;merged.isPickable=false;return merged;}
 factory(side,role,rank){const key=[side,role,rank].join('/');if(this.factories[key])return this.factories[key];const team=side===1?'blue':'red',trim=rank===2?'gold':'steel',group=(n,fn)=>this.group(key+'/'+n,fn),templates={};
 templates.body=group('torso',a=>{a('cyl',[.264,.203,.52],[0,0,0],team);a('cyl',[.163,.249,.13],[0,.24,0],'iron');const strap=a('box',[.057,.55,.034],[.08,0,.218],'strap');strap.rotation.z=-.23;for(const s of [-1,1])a('sphere',[.245,.12,.28],[s*.267,.202,0],trim);a('box',[.45,.60,.035],[0,-.04,-.238],side===1?'red':'pine');if(role==='archer'){const q=a('cyl',[.075,.075,.56],[-.16,.03,-.28],'leather');q.rotation.z=.3;for(let i=0;i<3;i++)a('cyl',[.007,.007,.42],[-.18+i*.03,.43,-.29],'pale');}});
 templates.hips=group('pelvis',a=>{a('cyl',[.21,.25,.27],[0,0,0],team);a('cyl',[.22,.224,.07],[0,.136,0],'leather');a('box',[.073,.06,.03],[0,.14,.23],'gold');for(let i=0;i<8;i++){const t=i*Math.PI/4,p=a('box',[.12,.30,.028],[Math.sin(t)*.218,-.13,Math.cos(t)*.218],i%3?'leather':'strap');p.rotation.y=t;}});
 templates.head=group('head',a=>{a('sphere',[.258,.31,.244],[0,0,.027],'skin');a('sphere',[.05,.07,.065],[0,.005,.156],'skin');if(rank||role==='archer')a('sphere',[.23,.166,.126],[0,-.09,.1],'beard');a('cyl',[.032,.167,.23],[0,.16,0],trim);a('cyl',[.173,.174,.04],[0,.06,0],'iron');a('box',[.027,.154,.028],[0,.012,.17],trim);for(const s of [-1,1])a('sphere',[.02,.013,.016],[s*.058,.048,.141],'iron');});
 templates.thigh=group('thigh',a=>a('cyl',[.085,.102,1],[0,0,0],team));templates.shin=group('shin',a=>a('cyl',[.073,.065,1],[0,0,0],'leather'));templates.upper=group('upper arm',a=>a('cyl',[.083,.068,1],[0,0,0],team));templates.fore=group('forearm',a=>a('cyl',[.067,.058,1],[0,0,0],'leather'));templates.knee=group('knee',a=>a('sphere',[.18,.19,.18],[0,0,0],trim));templates.hand=group('glove',a=>a('sphere',[.12,.14,.114],[0,0,0],'leather'));
 templates.foot=group('boot',a=>{a('box',[.16,.048,.33],[0,-.079,.045],'iron');a('sphere',[.167,.11,.245],[0,-.02,.091],'leather');a('box',[.144,.097,.145],[0,-.031,-.073],'leather');a('cyl',[.078,.078,.20],[0,.07,-.017],'leather');a('cyl',[.082,.082,.027],[0,.13,-.017],'strap');});
 if(role!=='archer'){
 templates.shield=group('round shield',(a,arr)=>{const disk=a('cyl',[.355,.355,.053,32],[0,0,0],'wood');disk.rotation.x=Math.PI/2;const ring=B.MeshBuilder.CreateTorus('rim',{diameter:.72,thickness:.031,tessellation:32},this.scene);ring.rotation.x=Math.PI/2;ring.material=this.m[trim];arr.push(ring);for(let i=-3;i<=3;i++){const x=i*.083,h=2*Math.sqrt(.34*.34-x*x);a('box',[.005,h,.006],[x,0,.03],'leather');}for(let q=0;q<4;q++){const mesh=new B.Mesh('paint',this.scene),vd=new B.VertexData(),verts=[0,0,.034],indices=[];for(let j=0;j<=7;j++){const t=q*Math.PI/2+.08+j*(Math.PI/2-.16)/7;verts.push(Math.cos(t)*.30,Math.sin(t)*.30,.034);if(j)indices.push(0,j,j+1);}vd.positions=verts;vd.indices=indices;vd.uvs=new Array(verts.length/3*2).fill(0);vd.normals=[];B.VertexData.ComputeNormals(verts,indices,vd.normals);vd.applyToMesh(mesh);mesh.material=this.m[q%2?'pale':team];mesh.material.backFaceCulling=false;arr.push(mesh);}a('sphere',[.18,.18,.093],[0,0,.064],trim);for(let i=0;i<8;i++){const t=i*Math.PI/4;a('sphere',[.022,.022,.016],[Math.cos(t)*.327,Math.sin(t)*.327,.037],'gold');}});
 templates.sword=group('sword',a=>{a('cyl',[.023,.026,.18],[0,0,0],'leather');a('sphere',[.07,.045,.05],[0,-.12,0],'gold');a('box',[.23,.036,.045],[0,.12,0],'steel');a('box',[.05,.58,.017],[0,.43,0],'edge');const tip=a('cyl',[0,.029,.16,4],[0,.79,0],'edge');tip.rotation.y=Math.PI/4;});
 }else{
 templates.bow=group('bow',(a,arr)=>{const path=[];for(let i=0;i<=18;i++){const t=-1.2+i*2.4/18;path.push(new V(0,Math.sin(t)*.48,Math.cos(t)*.21-.08));}const bow=B.MeshBuilder.CreateTube('yew',{path,radius:.018,tessellation:6},this.scene);bow.material=this.m.wood;arr.push(bow);});
 }
 return this.factories[key]=templates;
 }
 warrior(u){const templates=this.factory(u.side,u.role,u.rank),root=new B.TransformNode('soldier '+u.id,this.scene),parts={};const instance=(name,key)=>{const i=templates[key].createInstance(u.id+'/'+name);i.parent=root;i.isVisible=true;i.isPickable=false;parts[name]=i;return i;};for(const k of ['hips','body','head'])instance(k,k);for(const s of ['L','R'])for(const p of ['thigh','shin','upper','fore','knee','hand','foot'])instance(p+s,p);if(u.role==='archer'){instance('bow','bow');parts.string=B.MeshBuilder.CreateLines('bowstring',{points:[V.Zero(),new V(0,1,0),new V(0,2,0)],updatable:true},this.scene);parts.string.parent=root;parts.string.color=color('#dbcaa4');parts.string.isPickable=false;}else{instance('shield','shield');instance('sword','sword');}
 this.shadow.addShadowCaster(parts.body);this.shadow.addShadowCaster(parts.head);if(parts.shield)this.shadow.addShadowCaster(parts.shield);return{root,parts};}
 orientY(mesh,d){const dir=new V(d.x,d.y,d.z).normalize(),dot=V.Dot(V.Up(),dir);mesh.rotationQuaternion=dot>.999999?B.Quaternion.Identity():dot<-.999999?B.Quaternion.RotationAxis(V.Right(),Math.PI):B.Quaternion.RotationAxis(V.Cross(V.Up(),dir).normalize(),Math.acos(clamp(dot,-1,1)));}
 pose(u,rig){const {root,parts:p}=rig,j=u.pose.joints,origin=new V(u.root.x,heightAt(u.root.x,u.root.z),u.root.z),put=(mesh,pt)=>mesh.position.set(pt.x-origin.x,pt.y-origin.y,pt.z-origin.z),seg=(mesh,a,b)=>{put(mesh,{x:(a.x+b.x)/2,y:(a.y+b.y)/2,z:(a.z+b.z)/2});const d={x:b.x-a.x,y:b.y-a.y,z:b.z-a.z};mesh.scaling.y=Math.hypot(d.x,d.y,d.z);this.orientY(mesh,d);};
 root.position.copyFrom(origin);if(u.dead){const t=this.battle.time-u.deathTime;root.rotation.z=-u.side*clamp(t*2,0,1)*1.48;root.position.y-=.04;if(t>12)root.setEnabled(false);}else root.rotation.z=0;
 put(p.hips,j.pelvis);p.hips.rotation.y=u.yaw;put(p.body,{x:j.pelvis.x,y:j.pelvis.y+.35,z:j.pelvis.z});p.body.rotation.y=u.yaw;put(p.head,j.head);p.head.rotation.y=u.yaw;
 for(const s of ['L','R']){seg(p['thigh'+s],j['hip'+s],j['knee'+s]);seg(p['shin'+s],j['knee'+s],j['ankle'+s]);seg(p['upper'+s],j['shoulder'+s],j['elbow'+s]);seg(p['fore'+s],j['elbow'+s],j['hand'+s]);put(p['knee'+s],j['knee'+s]);put(p['hand'+s],j['hand'+s]);const f=u.pose.feet[s==='L'?0:1];put(p['foot'+s],f.pos);const slope=(heightAt(f.pos.x+Math.sin(f.yaw)*.1,f.pos.z+Math.cos(f.yaw)*.1)-heightAt(f.pos.x,f.pos.z))/.1;p['foot'+s].rotation.set(f.pitch-Math.atan(slope),f.yaw,0);}
 if(p.shield){put(p.shield,u.pose.shieldCenter);p.shield.rotation.set(u.pose.shieldTilt,u.pose.shieldYaw,0);put(p.sword,j.handR);this.orientY(p.sword,u.pose.swordDir);}else{put(p.bow,j.handL);p.bow.rotation.y=u.yaw;const h=j.handL,tip=dy=>{const z=.21*Math.cos(1.2)-.08;return new V(h.x-origin.x+Math.sin(u.yaw)*z,h.y-origin.y+dy,h.z-origin.z+Math.cos(u.yaw)*z);};const hand=j.handR;B.MeshBuilder.CreateLines('bowstring',{points:[tip(-.448),new V(hand.x-origin.x,hand.y-origin.y,hand.z-origin.z),tip(.448)],instance:p.string},this.scene);}
 }
 buildTerrain(){const scene=this.scene;let seed=13481;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 const ground=this.ground=B.MeshBuilder.CreateGround('valley',{width:66,height:44,subdivisions:100,updatable:true},scene),pos=ground.getVerticesData(B.VertexBuffer.PositionKind),norm=[],colors=[];for(let i=0;i<pos.length;i+=3){const x=pos[i],z=pos[i+2];pos[i+1]=heightAt(x,z);const road=Math.exp(-Math.pow((z-.7*Math.sin(x*.15))/1.4,4)),variation=Math.sin(x*1.4+z*.8)*.016+Math.cos(z*2.3-x)*.012+(rnd()-.5)*.055,river=Math.abs(z-(8.2+Math.sin(x*.13)*1.5))<1;const grass=[.37,.414,.29],dirt=[.46,.409,.31];for(let c=0;c<3;c++)colors.push((river?[.29,.32,.27][c]:grass[c]*(1-road)+dirt[c]*road)+variation);colors.push(1);}ground.updateVerticesData(B.VertexBuffer.PositionKind,pos);B.VertexData.ComputeNormals(pos,ground.getIndices(),norm);ground.updateVerticesData(B.VertexBuffer.NormalKind,norm);ground.setVerticesData(B.VertexBuffer.ColorKind,colors);ground.material=this.m.land;ground.receiveShadows=true;ground.isPickable=true;ground.refreshBoundingInfo();
 const waterMat=new B.StandardMaterial('stream',scene);waterMat.diffuseColor=color('#6a9691');waterMat.specularColor=color('#cfdecf');waterMat.specularPower=72;waterMat.alpha=.78;const paths=[[],[]];for(let x=-33;x<=33;x++){const z=8.2+Math.sin(x*.13)*1.5;paths[0].push(new V(x,heightAt(x,z)+.018,z-.60));paths[1].push(new V(x,heightAt(x,z)+.018,z+.60));}this.water=B.MeshBuilder.CreateRibbon('river',{pathArray:paths,sideOrientation:B.Mesh.DOUBLESIDE},scene);this.water.material=waterMat;this.water.isPickable=false;
 // Shared pine geometry; irregular crowns rather than repeated 2D billboards.
 const pine=this.group('pine',(a,arr)=>{a('cyl',[.05,.12,2.5,7],[0,1.25,0],'wood');for(let k=0;k<5;k++){const mesh=B.MeshBuilder.CreateCylinder('pine crown',{diameterTop:.06,diameterBottom:2.25-k*.31,height:1.8-k*.08,tessellation:9},scene);mesh.position.y=1.8+k*.52;mesh.rotation.y=k*.78;mesh.material=this.m[k%2?'pine':'pineLight'];arr.push(mesh);}});
 for(let i=0;i<78;i++){const x=(rnd()-.5)*62,z=(rnd()>.42?1:-1)*(7+rnd()*12);if(Math.abs(x)<18&&z<9&&z>-8)continue;const inst=pine.createInstance('fir'+i);inst.isVisible=true;inst.position.set(x,heightAt(x,z),z);inst.rotation.y=rnd()*6.28;const s=.65+rnd()*.70;inst.scaling.set(s,s,s);inst.isPickable=false;if(i%3===0)this.shadow.addShadowCaster(inst);}
 const rock=B.MeshBuilder.CreateIcoSphere('rock',{radius:1,subdivisions:1,flat:true},scene);rock.material=this.m.stone;rock.isVisible=false;rock.isPickable=false;for(let i=0;i<150;i++){let x=(rnd()-.5)*61,z=(rnd()-.5)*35;if(Math.abs(x)<18&&Math.abs(z)<5.2)continue;const s=.16+rnd()*.80,r=rock.createInstance('boulder'+i);r.position.set(x,heightAt(x,z)+s*.24,z);r.scaling.set(s,s*.65,s*.85);r.rotation.set(rnd()*.7,rnd()*6,0);r.isVisible=true;r.isPickable=false;}
 const grass=this.group('grass tuft',(a,arr)=>{for(let j=0;j<3;j++){const mesh=B.MeshBuilder.CreatePlane('blade',{width:.035,height:.35,sideOrientation:B.Mesh.DOUBLESIDE},scene);mesh.position.set((j-1)*.038,.17,0);mesh.rotation.set(.1,j*1.2,(j-1)*.16);mesh.material=this.m.pineLight;arr.push(mesh);}});
 const matrices=[];for(let i=0;i<1450;i++){const x=(rnd()-.5)*61,z=(rnd()-.5)*34;if(Math.abs(z-.7*Math.sin(x*.15))<1.6||Math.abs(z-(8.2+Math.sin(x*.13)*1.5))<1)continue;const s=.55+rnd()*.8;const matrix=B.Matrix.Compose(new V(s,s,s),B.Quaternion.RotationAxis(V.Up(),rnd()*6.28),new V(x,heightAt(x,z),z));matrices.push(...matrix.m);}grass.isVisible=true;grass.thinInstanceSetBuffer('matrix',new Float32Array(matrices),16,true);grass.thinInstanceRefreshBoundingInfo();
 // A wooden crossing in the background and low ruined walls frame the playable meadow.
 const bridgeZ=8.2+Math.sin(6*.13)*1.5,bridgeY=heightAt(6,bridgeZ)+.12;for(let i=0;i<12;i++)this.primitive('box','bridge board',[1.9,.10,.22],[6,bridgeY,bridgeZ-1.25+i*.23],'wood');for(const x of [5.10,6.90]){for(const z of [bridgeZ-1.25,bridgeZ+1.25])this.primitive('cyl','bridge post',[.04,.05,.75],[x,bridgeY+.30,z],'wood');this.primitive('box','rail',[.07,.08,2.8],[x,bridgeY+.58,bridgeZ],'strap');}
 for(const side of [-1,1]){for(let i=0;i<12;i++){const x=side*22,z=-4+i*.72;this.primitive('cyl','palisade',[.025,.13,1.8,7],[x,heightAt(x,z)+.9,z],'wood');}for(let i=0;i<9;i++){const x=side*(15+i%3*.72),z=-8+Math.floor(i/3)*.55;this.primitive('box','ruin',[.69,.55,.5],[x,heightAt(x,z)+.25+(i%2)*.20,z],'stone');}}
 for(const x of [-19,19]){const pts=[];for(let z=-5;z<=5;z+=.4)pts.push(new V(x,heightAt(x,z)+.025,z));const line=B.MeshBuilder.CreateDashedLines('rupture line',{points:pts,dashSize:.4,gapSize:.22,dashNb:30},scene);line.color=color('#b8955d');line.isPickable=false;}
 }
 buildFlags(){this.flags=[];for(const side of [1,-1]){const root=new B.TransformNode('banner',this.scene),pole=this.primitive('cyl','standard',[.022,.025,3],[0,1.5,0],'wood');pole.parent=root;const cloth=B.MeshBuilder.CreateGround('banner cloth',{width:1.2,height:.70,subdivisions:7,updatable:true},this.scene);cloth.rotation.x=-Math.PI/2;cloth.position.set(.58,2.4,0);cloth.material=this.m[side===1?'blue':'red'];cloth.material.backFaceCulling=false;cloth.parent=root;cloth.isPickable=false;const base=cloth.getVerticesData(B.VertexBuffer.PositionKind).slice();this.flags.push({root,cloth,base,side});}}
 mark(point){this.destinationAge=0;this.destination.position.set(point.x,heightAt(point.x,point.z)+.03,point.z);this.destination.setEnabled(true);}
 pick(x,y){const rect=this.canvas.getBoundingClientRect();/* Babylon applies hardware scaling internally: supply CSS coordinates. */const r=this.scene.pick(x-rect.left,y-rect.top,m=>m===this.ground);return r&&r.hit?r.pickedPoint:null;}
 zoom(delta){this.radius=clamp(this.radius+delta,13,45);}
 cameraMode(mode){this.mode=mode;this.radius=mode==='close'?16:35;}
 update(dt){this.time+=dt;this.destinationAge+=dt;if(this.destinationAge>2.5)this.destination.setEnabled(false);for(const u of this.battle.units){if(!this.units.has(u.id))this.units.set(u.id,this.warrior(u));this.pose(u,this.units.get(u.id));}
 const target=this.mode==='close'?new V(this.battle.player.x,1,this.battle.player.z):new V((this.battle.player.x+this.battle.enemy.x)*.20,.1,0),k=1-Math.exp(-dt*3);this.camera.target=B.Vector3.Lerp(this.camera.target,target,k);this.camera.radius+=(this.radius-this.camera.radius)*k;this.camera.beta+=((this.mode==='close'?1.02:.71)-this.camera.beta)*k;
 for(const f of this.flags){const a=f.side===1?this.battle.player:this.battle.enemy;f.root.position.set(a.x-f.side*2.5,heightAt(a.x-f.side*2.5,a.z+3.8),a.z+3.8);const p=f.base.slice();for(let i=0;i<p.length;i+=3)p[i+1]=Math.sin(p[i]*4+this.time*3)*.06*(p[i]+.6);f.cloth.updateVerticesData(B.VertexBuffer.PositionKind,p);}
 const current=new Set();for(const a of this.battle.arrows){current.add(a.id);let mesh=this.projectiles.get(a.id);if(!mesh){mesh=this.primitive('cyl','arrow',[.009,.009,.70,5],[0,0,0],'pale');this.projectiles.set(a.id,mesh);}const t=clamp(a.t/a.duration,0,1),arc=2.4,pt={x:a.from.x+(a.to.x-a.from.x)*t,y:a.from.y+(a.to.y-a.from.y)*t+arc*4*t*(1-t),z:a.from.z+(a.to.z-a.from.z)*t};mesh.position.set(pt.x,pt.y,pt.z);this.orientY(mesh,{x:a.to.x-a.from.x,y:a.to.y-a.from.y+arc*4*(1-2*t),z:a.to.z-a.from.z});}
 for(const [id,mesh]of this.projectiles)if(!current.has(id)){mesh.dispose();this.projectiles.delete(id);}
 for(const ev of this.battle.drainEvents())if(['hit','block'].includes(ev.type)){for(let i=0;i<3;i++){const mesh=this.primitive('sphere','impact',[.042,.042,.042],[ev.x,ev.y,ev.z],ev.type==='block'?'gold':'strap');this.effects.push({mesh,life:.32,vx:(i-1)*.8,vz:Math.sin(i*3)*.8});}}
 for(const e of this.effects){e.life-=dt;e.mesh.position.x+=e.vx*dt;e.mesh.position.z+=e.vz*dt;e.mesh.position.y+=dt*(e.life*2-.5);e.mesh.scaling.setAll(clamp(e.life/.32,0,1));if(e.life<=0)e.mesh.dispose();}this.effects=this.effects.filter(e=>e.life>0);
 this.scene.render();
 }
 resize(){this.engine.resize();}
 dispose(){this.scene.dispose();this.engine.dispose();}
}
g.RDNBattleView=BattleView;
})(globalThis);
