/* Bootstrap, touch input and accessible DOM UI. No fullscreen/orientation lock. */
(function(){'use strict';const $=id=>document.getElementById(id),canvas=$('scene');let game=null,view=null,last=0,uiClock=0,ready=false,disposed=false;const errors=[];
const portrait=()=>matchMedia('(pointer:coarse)').matches&&innerHeight>innerWidth;
function failure(message){ready=false;$('loading').hidden=false;$('loadMessage').textContent=message;$('retry').hidden=false;errors.push(message);document.querySelectorAll('.order,.views button').forEach(b=>b.disabled=true);}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');let finished=false;const timer=setTimeout(()=>done(false),12000);function done(ok){if(finished)return;finished=true;clearTimeout(timer);s.onload=s.onerror=null;if(!ok)s.remove();ok?resolve():reject(new Error('Chargement impossible : '+src));}s.onload=()=>done(true);s.onerror=()=>done(false);s.src=src;document.head.appendChild(s);});}
async function init(){try{if(!globalThis.RDNMotion||!globalThis.RDNBattle)throw new Error('Les fichiers du jeu ne sont pas tous chargés.');for(const url of ['https://cdn.jsdelivr.net/npm/babylonjs@8.26.0/babylon.js','https://unpkg.com/babylonjs@8.26.0/babylon.js']){try{await loadScript(url);if(globalThis.BABYLON)break;}catch(e){errors.push(e.message);}}if(!globalThis.BABYLON)throw new Error('Le moteur 3D est inaccessible. Vérifiez la connexion puis réessayez.');if(!BABYLON.Engine.isSupported())throw new Error('La 3D WebGL est indisponible dans cette fenêtre. Ouvrez le lien dans Safari.');await loadScript('battle-view.js');game=new RDNBattle.Battle();view=new RDNBattleView(canvas,game);view.update(0);ready=true;$('loading').hidden=true;document.querySelectorAll('.views button').forEach(b=>b.disabled=false);updateUI();last=performance.now();requestAnimationFrame(frame);}catch(e){failure(e.message);}}
function issue(cmd,point){if(!ready||!game)return;if(portrait()){$('notice').textContent='Tournez l’iPhone à l’horizontale pour commander.';return;}if(game.issue(cmd,point)&&point)view.mark(point);updateUI();}
function updateUI(){if(!game)return;const s=game.summary(),blocked=['paused','defeat','victory'].includes(s.state);$('ours').textContent=s.player;$('theirs').textContent=s.enemy;$('morale').textContent=s.morale;$('courage').textContent=s.courage;$('moraleFill').style.width=s.morale+'%';$('courageFill').style.width=s.courage+'%';$('notice').textContent=s.state==='paused'?'Bataille en pause — appuyez sur Reprendre.':s.notice;$('notice').classList.toggle('warn',s.order==='retreat');$('formLabel').textContent=({line:'Ligne',wall:'Mur',wedge:'Pointe',loose:'Écartée'})[s.formation];$('volleyLabel').textContent=s.volleyWait>0?'Recharge '+s.volleyWait.toFixed(1)+' s':'Volée d’archers';$('recruitLabel').textContent=s.recruited?'Déjà appelées':'+6 combattants';$('pause').textContent=s.state==='paused'?'Reprendre':'Pause';$('wave').textContent='Vague '+s.wave+' · 3D articulée';$('clock').textContent=s.state==='ready'?'Donnez un ordre':s.state==='paused'?'En pause':s.remaining>0?s.remaining.toFixed(1)+' s avant repli':'L’armée recule';$('orderFill').style.width=(s.state==='ready'?100:s.remaining/5*100)+'%';for(const b of document.querySelectorAll('[data-command]')){const c=b.dataset.command;b.disabled=!ready||blocked||(c==='charge'&&s.courage<30)||(c==='volley'&&s.volleyWait>0)||(c==='recruit'&&s.recruited);b.classList.toggle('active',c==='shield'&&s.order==='shield'||c==='charge'&&s.order==='charge'||c==='volley'&&s.order==='volley');b.setAttribute('aria-pressed',b.classList.contains('active'));}$('finish').hidden=!['victory','defeat'].includes(s.state);if(!$('finish').hidden){$('finishTitle').textContent=s.state==='victory'?'La ligne a cédé.':'Le repli de la garnison.';$('finishText').textContent=s.state==='victory'?'Victoire · '+s.player+' survivants gagnent de l’expérience.':'Défaite · '+s.player+' combattants encore debout.';$('next').textContent=s.state==='victory'?'Bataille suivante':'Recommencer';}}
function frame(now){if(disposed)return;try{const dt=Math.min((now-last)/1000,.05);last=now;if(portrait()&&game.state==='running')game.pause();game.step(dt);view.update(dt);uiClock+=dt;if(uiClock>.12){updateUI();uiClock=0;}requestAnimationFrame(frame);}catch(e){failure('Erreur de rendu : '+e.message);}}
const touches=new Map();let gesture=null,pinchDistance=0,multi=false;
canvas.addEventListener('pointerdown',e=>{if(!ready)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===1){gesture={x:e.clientX,y:e.clientY};multi=false;}else{multi=true;const pts=[...touches.values()];pinchDistance=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);}});
canvas.addEventListener('pointermove',e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touches.size===2){const pts=[...touches.values()],d=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);view.zoom((pinchDistance-d)*.04);pinchDistance=d;}else if(!multi){const p=view.pick(e.clientX,e.clientY);if(p)view.mark(p);}});
canvas.addEventListener('pointerup',e=>{if(!touches.has(e.pointerId))return;if(!multi&&gesture){const p=view.pick(e.clientX,e.clientY);if(p)issue('move',p);}touches.delete(e.pointerId);if(!touches.size){gesture=null;multi=false;}if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);});
const cancel=e=>{touches.delete(e.pointerId);gesture=null;multi=true;};canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('lostpointercapture',e=>{if(touches.has(e.pointerId))cancel(e);});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{if(view){e.preventDefault();view.zoom(Math.sign(e.deltaY)*2);}},{passive:false});
for(const b of document.querySelectorAll('[data-command]'))b.addEventListener('click',()=>issue(b.dataset.command));$('hold').addEventListener('click',()=>issue('hold'));$('pause').addEventListener('click',()=>{if(game){game.pause();updateUI();}});$('view').addEventListener('click',()=>{const close=view.mode!=='close';view.cameraMode(close?'close':'tactical');$('view').textContent=close?'Tactique':'Rapproché';$('view').setAttribute('aria-pressed',close);});$('minus').addEventListener('click',()=>view.zoom(3));$('plus').addEventListener('click',()=>view.zoom(-3));$('retry').addEventListener('click',()=>location.reload());$('next').addEventListener('click',()=>{const next=game.state==='victory'?game.nextWave():new RDNBattle.Battle();view.dispose();game=next;view=new RDNBattleView(canvas,game);updateUI();});
addEventListener('resize',()=>{if(view)view.resize();if(game&&portrait()&&game.state==='running'){game.pause();updateUI();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game&&game.state==='running'){game.pause();updateUI();}last=performance.now();});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(game&&game.state==='running')game.pause();disposed=true;failure('La session 3D a été interrompue. Rechargez pour reprendre une bataille.');});
addEventListener('keydown',e=>{if(e.code==='Space'&&game){e.preventDefault();game.pause();updateUI();}const cmd={Digit1:'formation',Digit2:'shield',Digit3:'charge',Digit4:'volley',Digit5:'recruit'}[e.code];if(cmd)issue(cmd);});
globalThis.RDNDebug={get ready(){return ready;},get game(){return game;},get view(){return view;},errors,issue};init();})();
